### ISSUE TITLE
cleanup on plugin uninstall

### ISSUE THREAD

**Issue by diggy** [vyskoczilova/woocommerce-payforpayment#17]

**Comment by vyskoczilova** [comment]
@diggy Anything you wanted to say or do?

And if you feel like having a few minutes of spare time, could you check the new WPML filters I have added in the last commit? Two days ago, I made the strings translatable within String translations in WPML, but newly translated strings are not displaying (maybe I've missed something). Otherwise it will wait for a WPML guy.

**Comment by diggy** [comment]
@vyskoczilova the plugin adds items to gateway settings arrays, so I guess these items should be removed again on plugin uninstall.

I try to avoid WPML as much as possible :) Maybe you should try the `wpml-config.xml` approach? Will be picked up by Polylang as well.

**Comment by vyskoczilova** [comment]
@diggy  true, when I will have spare time, I will add the remove feature on uninstall (but I'm quite busy throught)

I see, a `wpml-config.xml` approach was used until the latest version, but I want to drop it off cause the problem is that I can't predict which gateways will be available and every gateway which is not present within `wpml-config.xml` is untranslatable. Using WPML filters should fix this trouble (when used correctly).

**Comment by vyskoczilova** [comment]
Hey bot, I know about the issue, I will have a look on it later.

**Comment by vyskoczilova** [comment]
Hey bot, I know about the issue, I will have a look on it later.

**Comment by vyskoczilova** [comment]
Hey bot, I know about the issue, I will have a look on it later.

**Comment by vyskoczilova** [comment]
Hey bot, I know about the issue, I will have a look on it later.

**Comment by vyskoczilova** [comment]
Hey bot, I know about the issue, I will have a look on it later.

**Comment by vyskoczilova** [comment]
Hey bot, I know about the issue, I will have a look on it later.

**Comment by vyskoczilova** [comment]
Hey bot, I know about the issue, I will have a look on it later.
