### ISSUE TITLE
Plugin Settings enhancements

### ISSUE THREAD

**Issue by thierrydev** [vyskoczilova/woocommerce-payforpayment#56]
I came across your plugin at work and while it's very nice to offer this functionality, I think you are missing a few critical functionalities, I encourage you to take the following steps to make life easier for others.

I had to modify the plugin's code to exclude my plugin from any modifications and that was quite annoying and unnecessary.

- Add proper settings page
- Add setting to exclude for  payment methods mentioned in plugin's settings

**Comment by vyskoczilova** [comment]
Hi @thierrydev,

could you be more specific?

What do you mean by "Add proper settings page"? Since the fee is related to the payment gateways, the settings are extending the gateway. What you miss or what you'd like to have on a settings page?

I'm not sure what do you want to achieve with excluding payment methods in the settings. In the very first place, if you haven't activated the fee for a gateway, the fee is not added and there is no need to exclude... But maybe I got something wrong.

I'm keen to see which plugin you're talking about and what you needed to exclude. If it's something that makes sense, feel free to open a PR.

Looking forward to hearing from you
Karolina

**Comment by thierrydev** [comment]
Hello thanks for your quick reply

I will submit a PR with the quickest way to solve this when I have time.

For the long term I suggest that you look into inserting and querying the fees from the DB instead of doing all the changes "live"

Add a layer between the gateways and the settings by storing the fees in the database instead of doing live changes.

**Comment by vyskoczilova** [comment]
Hi, I'm really keen to see, what do you mean by that since I'm still bit lost which part is the problematic one.

The plugin is using standard WC_Fee and it's integrations. So in long term, this should be a safe and sustainable way to do it, since it's recommended.
